### ISSUE TITLE
widgets interact not presenting a slider

### ISSUE THREAD

**Issue by afonit** [QuantStack/voila#85]
```
# Name                    Version                   Build  Channel
voila                     0.0.9                      py_0    conda-forge
```

I did see this:
https://github.com/QuantStack/voila/issues/19

And I am able to get widgets working using the pattern shown in that report.

However when I use widgets in other patterns like the below they don't work:

```python
import ipywidgets as widgets
from ipywidgets import interact

def what(item):
    return item*5
interact(what, item=widgets.IntSlider(value=2, min=1, max=10))
```

Here is what it looks like with voila:
![image](https://user-images.githubusercontent.com/1798497/54455123-61b91580-4731-11e9-9952-ce6afdd932c6.png)

Here is the chrome console output:
![image](https://user-images.githubusercontent.com/1798497/54455185-8a410f80-4731-11e9-903e-6b2bfdb39965.png)

-----------------
Here is what the jupyter widget looks like in the regular notebook:
![image](https://user-images.githubusercontent.com/1798497/54455044-37675800-4731-11e9-9c59-80ab3b26a922.png)

**Comment by maartenbreddels** [comment]
I've been digging into this, and the source of the problem is that nbconvert gets a [clear_output](https://github.com/jupyter/nbconvert/blob/0ef92837822da09821b96955074002726b08a99f/nbconvert/preprocessors/execute.py#L478) after the output msg. Since voila uses nbconvert, we have the same issue.
To see the issue, put the code in a notebook, and execute:
```
python -m nbconvert ~/src/QuantStack/voila/issue/85.ipynb --to ipynb --log-level=DEBUG --execute --stdout
```
I see the output as an empty list. It was also noted by @SylvainCorlay in item 3 at #19

**Comment by maartenbreddels** [comment]
https://github.com/jupyter/nbconvert/pull/969 partly solves the issue, I still have difficulty getting the output to show. TBC.

**Comment by maartenbreddels** [comment]
This should be solved by https://github.com/QuantStack/voila/pull/91
using master voila and master nbconvert it should work, for testing it needs the branch that is used in .travis.yml

**Comment by psychemedia** [comment]
Is this fix going to be released any time soon? I think the current pip version is still showing this issue?

**Comment by afeiszli** [comment]
Just tried out voila and had the same issue with interact. Installed using pip.

**Comment by leogout** [comment]
Hello, I have the same problem, to fix this I had to install Jupyterlab + Ipywidgets in my project directory:
```
pip install jupyterlab ipywidgets voila
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

**Comment by maartenbreddels** [comment]
Make sure you have voila 0.0.10 and nbconvert 5.5+, let us know if that does or does not solve it.

**Comment by leogout** [comment]
I'm very sorry I must have missed something, it works like a charm now.

**Comment by maartenbreddels** [comment]
No problem, happy to hear it works!
